name: My custom CI

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        default: '3.8'
      coverage:
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if ${{ inputs.coverage }}; then 
              pip install coverage
              coverage run -m pytest
              coverage report -m
          else
              pytest
          fi
